spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: maelkifbusgcvu
    url: jdbc:postgresql://ec2-34-197-84-74.compute-1.amazonaws.com:5432/d5algqbqkvo3iu
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
